[tools]
# Languages
python = "3.14"
node = "25.8.2"

# Tools
fzf = "latest"
ripgrep = "latest"
fd = "latest"
eza = "latest"
stylua = "latest"
zoxide = "latest"
bat = "latest"
shfmt = "latest"
uv = "latest"
yq = "latest"
gh = "latest"
shellcheck = "latest"

# Agents
pi = "latest"

[settings]
python.uv_venv_auto = "create|source"

# mise use -g
